[workspace]
members = [
    "argon2",
    "audit",
    "randomx-sp1",
    "executor",
    "program",
    "randomx-core",
    "softfp",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false
rust-version = "1.91"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0"
baseline = { package = "rustdom-x-argon2", version = "=2.1.0" }
blake2b_simd = "=1.0.4"
hex = "=0.4.3"
randomx-softfp = { path = "softfp" }
randomx-sp1 = { path = "randomx-sp1" }
randomx-sp1-argon2 = { path = "argon2" }
randomx-sp1-core = { path = "randomx-core" }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "1"
softfloat = "=1.0.0"
softfloat-wrapper = "=0.3.4"
sp1-core-executor = "=6.3.1"
sp1-core-executor-runner = "=6.3.1"
sp1-zkvm = "=6.3.1"
strum = { version = "=0.27.2", features = ["derive"] }
tiny-keccak = { version = "=2.0.2", features = ["keccak"] }

[profile.release]
lto = "thin"
